### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by r3pt1s** [SayakaPM/ScrimAZ#5]
[11:13:47.790] [Server thread/CRITICAL]: ErrorException: "Undefined array key "r3pt1s"" (EXCEPTION) in "plugins/ScrimAZ.phar/src/Alert" at line 20
--- Stack trace ---
  #0 plugins/ScrimAZ.phar/src/Alert(20): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[28] Undefined array key "r3pt1s", string[68] phar://C:/Server/Testserver/PMMP4/plugins/ScrimAZ.phar/src/Alert.php, int 20)
  #1 plugins/ScrimAZ.phar/src/Checks/Movement/Speed(24): OnlyJaiden\ScrimAS\Alert->alert(string[5] Speed, string[6] r3pt1s)
  #2 pmsrc/src/event/RegisteredListener(60): OnlyJaiden\ScrimAS\Checks\Movement\Speed->onPlayerMove(object pocketmine\event\player\PlayerMoveEvent#127971)
  #3 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent#127971)
  #4 pmsrc/src/player/Player(1240): pocketmine\event\Event->call()
  #5 pmsrc/src/player/Player(1327): pocketmine\player\Player->processMostRecentMovements()
  #6 pmsrc/src/world/World(842): pocketmine\player\Player->onUpdate(int 6623)
  #7 pmsrc/src/world/World(768): pocketmine\world\World->actuallyDoTick(int 6623)
  #8 pmsrc/src/world/WorldManager(348): pocketmine\world\World->doTick(int 6623)
  #9 pmsrc/src/Server(1818): pocketmine\world\WorldManager->tick(int 6623)
  #10 pmsrc/src/Server(1700): pocketmine\Server->tick()
  #11 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #12 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[27] C:\Server\Testserver\PMMP4\, string[35] C:\Server\Testserver\PMMP4\plugins\)
  #13 pmsrc/src/PocketMine(327): pocketmine\server()
  #14 pmsrc(11): require(string[71] phar://C:/Server/Testserver/PMMP4/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by SayakaPM** [comment]
Thank for the issue i have fixed it i forgot to fix it so sorry.
